# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Don't stale on below labels
exemptLabels:
  - help wanted
  - feature
  - technical
  - watch
  - block
  - pinned
  - security

# Ignore issues in a project
exemptProjects: true

# Ignore issues in a milestone
exemptMilestones: true

# Ignore issues with an assignee
exemptAssignees: true
  
# Label to use when marking an issue as stale
staleLabel: wontfix

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because it didn't had recent activity.
